version: '2.6'
services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nyc_taxi
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  test-db:
#    image: postgres:17
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: test_analytics
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    ports:
#      - "5433:5433"

  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"

#  tests:
#    build: .
#    depends_on:
#      - web
#    command: >
#      sh -c "sleep 5 &&
#             python -m unittest tests/test_routes.py"

volumes:
  pgdata:
    name: pgdata
