# Generated by Django 5.2.1 on 2025-05-16 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datetime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_hour', models.IntegerField()),
                ('measurement_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Precipitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_hourly_precipitation_millimeters', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_hourly_temperature_celsius', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weather_app.datetime')),
                ('precipitation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weather_app.precipitation')),
                ('temperature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weather_app.temperature')),
                ('weather_station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weather_app.weatherstation')),
            ],
        ),
    ]
