"""add tip_amout column

Revision ID: df562ce1debb
Revises: f65915c9cf45
Create Date: 2025-05-17 17:56:03.032870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df562ce1debb'
down_revision: Union[str, None] = 'f65915c9cf45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_records', sa.Column('tip_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_records', 'tip_amount')
    # ### end Alembic commands ###
